theme = "varua"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
G = "goto_last_line"
K = "hover"
ret = ["open_below", "normal_mode"]
C-space = "expand_selection"
X = ["extend_line_up", "extend_to_line_bounds"]
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.normal.g]
c = "toggle_comments"
[keys.select.g]
c = "toggle_comments"

[keys.normal.Z]
Z = ":write-quit"
Q = ":quit!"
